<?php
namespace App;
use App\Model\UserTable;
use Chatbox\ApiAuth\Models\UserService;
use Chatbox\MailClerk\MailClerkServiceProvider;
use Chatbox\Token\CacheTokenService;
use Chatbox\ApiAuth\Domains\UserServiceInterface;

use Chatbox\MailAuth\Service\RegisterMailTokenService;
use Chatbox\MailAuth\Service\ProfileMailTokenService;
use Chatbox\MailAuth\Service\ResetMailTokenService;
use Illuminate\Mail\MailServiceProvider;

/**
 * Created by PhpStorm.
 * User: mkkn
 * Date: 2016/07/19
 * Time: 12:44
 */
class MailAuthServiceProvider extends \Chatbox\MailAuth\MailAuthServiceProvider
{
    public function register()
    {
        $this->app->register(MailClerkServiceProvider::class);
        return parent::register(); // TODO: Change the autogenerated stub
    }


    protected function registerUserServiceInterface():UserServiceInterface
    {
        $model = new UserTable();
        $token = new CacheTokenService(app("cache")->store());
        return new UserService($model,$token);
    }

    protected function registerRegisterMailTokenService():RegisterMailTokenService
    {
        $token = new CacheTokenService(app("cache")->store());
        return new \App\Services\RegisterMailTokenService($token);
    }

    protected function registerProfileMailTokenService():ProfileMailTokenService
    {
        // TODO: Implement registerProfileMailTokenService() method.
    }

    protected function registerResetMailTokenService():ResetMailTokenService
    {
        // TODO: Implement registerResetMailTokenService() method.
    }


}